Map<String, List<String>> carBrands = {
  "AC": [
    " ACE",
    " ACECA",
    " COBRA",
    " FRUA CONVERTIBLE",
    " FRUA COUPE",
  ],
  "ACURA": [
    "CL",
    "CSX",
    "EL",
    "ILX",
    "INTEGRA COUPE",
    "INTEGRA SEDAN",
    "LEGEND",
    "LEGEND COUPE",
    "MDX",
    "NSX",
    "RDX",
    "RL",
    "RLX",
    "RSX",
    "RSX TYPE-S",
    "SLX",
    "TL",
    "TLX",
    "TSX",
    "ZDX",
  ],
  "ALFA ROMEO": [
    "145",
    "146",
    "147 3 DOORS",
    "147 5 DOORS",
    "155",
    "156",
    "156 SPORTWAGON",
    "159",
    "159 SPORTWAGON",
    "164",
    "166",
    "1900",
    "2000",
    "24 HP",
    "2600",
    "33",
    "33 SPORT WAGON",
    "4C",
    "4C SPIDER",
    "6",
    "6C",
    "75",
    "8C",
    "ALFASUD",
    "ALFASUD GIARDINETTA",
    "ALFASUD SPRINT",
    "ALFASUD TI",
    "ALFETTA",
    "ARNA",
    "BRERA",
    "CROSSWAGON Q4",
    "GT",
    "GTV",
    "GIULIA",
    "GIULIA GTA",
    "GIULIA QUADRIFOGLIO",
    "GIULIA VELOCE",
    "GIULIETTA",
    "GIULIETTA QUADRIFOGLIO VERDE",
    "JUNIOR",
    "MITO",
    "MITO QUADRIFOGLIO VERDE",
    "MITO VELOCE",
    "MONTREAL",
    "RL",
    "RM",
    "SPIDER",
    "SPRINT",
    "STELVIO",
    "STELVIO QUADRIFOGLIO",
    "TIPO 33",
    "TONALE",
    "TORPEDO 20-30 HP",
  ],
  "ALPINE": [
    "A106",
    "A108",
    "A110",
    "A110S",
    "A290",
  ],
  "ARIEL": [
    "ATOM",
    "NOMAD",
  ],
  "ARO": [
    "10 SERIES",
    "24 SERIES",
    "IMS SERIES",
    "M SERIES",
  ],
  "ARTEGA": [
    "GT",
    "SCALO",
  ],
  "ASTON MARTIN": [
    "CYGNET",
    "DB AR1",
    "DB MARK III",
    "DB11",
    "DB11 VOLANTE",
    "DB12",
    "DB12 VOLANTE",
    "DB2",
    "DB4",
    "DB5",
    "DB6",
    "DB6 VOLANTE",
    "DB7",
    "DB7 VOLANTE",
    "DB9",
    "DB9 VOLANTE",
    "DBS",
    "DBS VOLANTE",
    "DBX",
    "LAGONDA",
    "ONE-77",
    "RAPIDE",
    "RAPIDE AMR",
    "RAPIDE E",
    "RAPIDE S",
    "V12 SPEEDSTER",
    "V12 VANTAGE",
    "V12 VANTAGE AMR",
    "V12 VANTAGE S ROADSTER",
    "V12 ZAGATO",
    "V8 VANTAGE",
    "V8 VANTAGE S",
    "V8 VANTAGE S ROADSTER",
    "V8 VOLANTE",
    "VALHALLA",
    "VANQUISH",
    "VANQUISH S",
    "VANQUISH VOLANTE",
    "VANTAGE GT12",
    "VANTAGE GT8",
    "VANTAGE ROADSTER",
    "VIRAGE",
    "VIRAGE VOLANTE",
    "VULCAN",
  ],
  "AUDI": [
    "100 COUPE",
    "100/ 200",
    "100/ 200 AVANT",
    "80 AVANT RS2",
    "80 AVANT S2",
    "80 S2",
    "80/ 90",
    "80/ 90 AVANT",
    "90",
    "A1",
    "A1 QUATTRO",
    "A1 SPORTBACK",
    "A2",
    "A3",
    "A3 CABRIOLET",
    "A3 SEDAN",
    "A3 SPORTBACK",
    "A3 ALLSTREET",
    "A4",
    "A4 ALLROAD",
    "A4 AVANT",
    "A4 CABRIOLET",
    "A4 DTM EDITION",
    "A5",
    "A5 CABRIOLET",
    "A5 SPORTBACK",
    "A6",
    "A6 AVANT",
    "A7",
    "A8",
    "A8 (D2)",
    "ALLROAD",
    "CABRIOLET",
    "COUPE",
    "COUPE S2",
    "Q2",
    "Q3",
    "Q3 SPORTBACK",
    "Q4 SPORTBACK",
    "Q4 E-TRON",
    "Q5",
    "Q5 SPORTBACK",
    "Q6",
    "Q7",
    "Q8",
    "Q8 SPORTBACK",
    "Q8 E-TRON",
    "QUATTRO",
    "R8",
    "R8 GT",
    "R8 GT SPYDER",
    "R8 SPYDER",
    "RS 3 SEDAN",
    "RS 3 SPORTBACK",
    "RS 4",
    "RS 4 AVANT",
    "RS 4 CABRIOLET",
    "RS 5",
    "RS Q3",
    "RS Q8",
    "RS5 CABRIOLET",
    "RS5 SPORTBACK",
    "RS6",
    "RS6 AVANT",
    "RS7 SPORTBACK",
    "S1",
    "S1 SPORTBACK",
    "S3",
    "S3 CABRIOLET",
    "S3 SEDAN",
    "S3 SPORTBACK",
    "S4",
    "S4 AVANT",
    "S4 CABRIOLET",
    "S5",
    "S5 CABRIOLET",
    "S5 SPORTBACK",
    "S6",
    "S6 AVANT",
    "S7 SPORTBACK",
    "S8",
    "S8 PLUS",
    "SQ2",
    "SQ5",
    "SQ5 SPORTBACK",
    "SQ6",
    "SQ7",
    "SQ8",
    "SQ8 E-TRON",
    "TT COUPE",
    "TT RS COUPE",
    "TT RS ROADSTER",
    "TT ROADSTER",
    "TYP R",
    "V8",
    "E-TRON",
    "E-TRON GT",
    "E-TRON SPORTBACK",
  ],
  "AURUS": [
    "SENAT",
  ],
  "BENTLEY": [
    "ARNAGE",
    "AZURE",
    "BENTAYGA",
    "BENTAYGA SPEED",
    "BROOKLANDS",
    "CONTINENTAL",
    "CONTINENTAL FLYING SPUR",
    "CONTINENTAL GT",
    "CONTINENTAL GTC",
    "FLYING SPUR",
    "MK VI SALOON",
    "MULLINER",
    "MULSANNE",
    "S1",
    "STATE LIMOUSINE",
    "T1",
    "T2",
  ],
  "BMW": [
    "1 SERIES",
    "1 SERIES 3 DOORS",
    "1 SERIES CABRIOLET",
    "1 SERIES COUPE",
    "1 SERIES M COUPE",
    "1 SERIES SEDAN",
    "1500/1600",
    "2 SERIES ACTIVE TOURER",
    "2 SERIES CONVERTIBLE",
    "2 SERIES COUPE",
    "2 SERIES GRAN COUPE",
    "2 SERIES GRAN TOURER",
    "2000 CS",
    "2002",
    "2800 CS",
    "3 SERIES  CABRIOLET",
    "3 SERIES COMPACT",
    "3 SERIES COUPE",
    "3 SERIES GRAN TURISMO",
    "3 SERIES SEDAN",
    "3 SERIES TOURING",
    "3.0 CSL",
    "3.0 CSI",
    "3/15 PS",
    "3/20 PS",
    "303",
    "3200",
    "326",
    "327",
    "328",
    "335",
    "4 SERIES CONVERTIBLE",
    "4 SERIES COUPE",
    "4 SERIES GRAN COUPE",
    "5 SERIES GRAN TURISMO",
    "5 SERIES SEDAN",
    "5 SERIES TOURING",
    "501/502",
    "502 COUPE",
    "503",
    "507",
    "6 SERIES CONVERTIBLE",
    "6 SERIES COUPE",
    "6 SERIES GRAN COUPE",
    "6 SERIES GRAN TURISMO",
    "7 SERIES",
    "8 SERIES",
    "8 SERIES CONVERTIBLE",
    "8 SERIES COUPE",
    "8 SERIES GRAN COUPE",
    "ISETTA",
    "M1",
    "M2",
    "M3 CABRIOLET",
    "M3 COUPE",
    "M3 SEDAN",
    "M3 TOURING",
    "M4",
    "M4 CS",
    "M4 CONVERTIBLE",
    "M4 GTS",
    "M5",
    "M5 TOURING",
    "M6 CABRIO",
    "M6 COUPE",
    "M6 GRAN COUPE",
    "M8 CONVERTIBLE",
    "M8 COUPE",
    "M8 GRAN COUPE",
    "X1",
    "X2",
    "X3",
    "X3 M",
    "X4",
    "X4 M",
    "X5",
    "X5 M",
    "X6",
    "X6 M",
    "X7",
    "XM",
    "Z1",
    "Z3 COUPE",
    "Z3 ROADSTER",
    "Z4 COUPE",
    "Z4 ROADSTER",
    "Z8",
    "I3",
    "I4",
    "I5",
    "I5 TOURING",
    "I7",
    "I8",
    "I8 ROADSTER",
    "IX",
    "IX M",
    "IX1",
    "IX2",
    "IX3",
  ],
  "BRISTOL": [
    "400",
    "402",
    "403",
    "404",
    "405",
    "406",
    "407",
    "408",
    "411",
    "412",
    "603",
    "BLENHEIM",
    "BULLET",
    "FIGHTER",
    "SERIES 6",
  ],
  "BUFORI": [
    "GENEVA",
    "LA JOYA",
    "MK I",
    "MK II",
    "V6I",
  ],
  "BUGATTI": [
    "BOLIDE",
    "CENTODIECI",
    "CHIRON",
    "DIVO",
    "EB 110",
    "LA VOITURE NOIRE",
    "MISTRAL",
    "TOURBILLON",
    "TYPE 10",
    "TYPE 101",
    "TYPE 18",
    "TYPE 19",
    "TYPE 2",
    "TYPE 23",
    "TYPE 251",
    "TYPE 30",
    "TYPE 38",
    "TYPE 40",
    "TYPE 41",
    "TYPE 43",
    "TYPE 44",
    "TYPE 46",
    "TYPE 49",
    "TYPE 5",
    "TYPE 50",
    "TYPE 55",
    "TYPE 57",
    "TYPE 64",
    "VEYRON",
  ],
  "BUICK": [
    "CASCADA",
    "CENTURY",
    "ENCLAVE",
    "ENCORE",
    "ENVISION",
    "ENVISTA",
    "GRAN SPORT",
    "LACROSSE",
    "LESABRE",
    "LUCERNE",
    "MODEL 21",
    "MODEL 26",
    "MODEL 27",
    "MODEL 32",
    "MODEL 33",
    "MODEL 38",
    "MODEL 39",
    "MODEL 41",
    "MODEL C",
    "PARK AVENUE",
    "RAINIER",
    "REATTA",
    "REGAL",
    "REGAL SPORTBACK",
    "RENDEZVOUS",
    "RIVIERA",
    "ROADMASTER",
    "SKYLARK",
    "SUPER RIVIERA",
    "TERRAZA",
    "VERANO",
  ],
  "CADILLAC": [
    "ATS",
    "ATS COUPE",
    "ATS-V",
    "ATS-V COUPE",
    "ALLANTE",
    "BLS",
    "BLS WAGON",
    "BROUGHAM",
    "CT4",
    "CT4-V",
    "CT5",
    "CT5-V",
    "CT6",
    "CTS",
    "CTS COUPE",
    "CTS SPORT WAGON",
    "CTS V-SERIES",
    "CTS-V COUPE",
    "CTS-V SPORT WAGON",
    "CATERA",
    "CELESTIQ",
    "DTS",
    "DEVILLE",
    "ELR",
    "ELDORADO",
    "ESCALADE",
    "ESCALADE ESV",
    "ESCALADE EXT",
    "LYRIQ",
    "OPTIQ",
    "RUNABOUT",
    "SRX",
    "STS",
    "SEVILLE",
    "VISTIQ",
    "XLR",
    "XLR V-SERIES",
    "XT4",
    "XT5",
    "XT6",
    "XTS",
  ],
  "CATERHAM": [
    "CSR",
    "CLASSIC",
    "ROADSPORT",
    "SEVEN 160",
    "SEVEN 620",
    "SUPERLIGHT",
    "SUPERSPORT",
    "THE SUPER SEVEN 1600",
  ],
  "CHEVROLET": [
    "AGILE",
    "ASTRO",
    "AVALANCHE",
    "AVEO / KALOS 3 DOORS",
    "AVEO / KALOS 5 DOORS",
    "AVEO / KALOS SEDAN",
    "BLAZER",
    "BOLT",
    "CAMARO",
    "CAMARO CONVERTIBLE",
    "CAPTIVA",
    "CAVALIER",
    "CELTA",
    "CHEVELLE",
    "CLASSIC",
    "COBALT COUPE",
    "COBALT SEDAN",
    "COLORADO DOUBLE CAB",
    "COLORADO EXTENDED CAB",
    "COLORADO REGULAR CAB",
    "CORVETTE CONVERTIBLE",
    "CORVETTE COUPE",
    "CORVETTE E-RAY",
    "CORVETTE Z06",
    "CORVETTE Z06 CONVERTIBLE",
    "CORVETTE ZR1",
    "CRUZE",
    "CRUZE - 5 DOORS",
    "CRUZE WAGON",
    "EPICA",
    "EQUINOX",
    "EVANDA",
    "EXPRESS",
    "HHR",
    "IMPALA",
    "IMPALA CONVERTIBLE",
    "IMPALA COUPE",
    "MALIBU",
    "MALIBU MAXX",
    "MATIZ / SPARK",
    "MONTE CARLO",
    "NOMAD",
    "NUBIRA / LACETTI",
    "ONIX",
    "ORLANDO",
    "PRISMA",
    "S-10",
    "SS",
    "SSR",
    "SILVERADO",
    "SILVERADO 2500HD",
    "SILVERADO 3500HD",
    "SILVERADO HYBRID",
    "SONIC HATCHBACK",
    "SONIC RS",
    "SONIC SEDAN",
    "SPARK EV",
    "SPIN",
    "SUBURBAN",
    "TACUMA",
    "TAHOE",
    "TRACKER",
    "TRAILBLAZER",
    "TRAVERSE",
    "TRAX",
    "UPLANDER",
    "VENTURE",
    "VOLT",
  ],
  "CHRYSLER": [
    "200",
    "200 CONVERTIBLE",
    "300",
    "300 SPORT COUPE",
    "300C",
    "300C TOURING",
    "300M",
    "AIRFLOW",
    "ASPEN",
    "CONCORDE",
    "CROSSFIRE",
    "CROSSFIRE ROADSTER",
    "DAYTONA",
    "GRAND VOYAGER (AS)",
    "IMPERIAL",
    "IMPERIAL ROADSTER",
    "LEBARON",
    "NEW YORKER",
    "PT CRUISER",
    "PT CRUISER CONVERTIBLE",
    "PACIFICA",
    "SARATOGA",
    "SEBRING CONVERTIBLE",
    "SEBRING COUPE",
    "SEBRING SEDAN",
    "SIX",
    "TOWN & COUNTRY",
    "VOYAGER",
  ],
  "CITROEN": [
    "2CV",
    "AMI",
    "AX 3 DOORS",
    "AX 5 DOORS",
    "AXEL",
    "BX",
    "BX BREAK",
    "BERLINGO",
    "C-CROSSER",
    "C-ELYSEE",
    "C-ZERO",
    "C1 3 DOORS",
    "C1 5 DOORS",
    "C2",
    "C3",
    "C3 AIRCROSS",
    "C3 PICASSO",
    "C3 PLURIEL",
    "C4",
    "C4 AIRCROSS",
    "C4 CACTUS",
    "C4 COUPE",
    "C4 HATCHBACK",
    "C4 PICASSO",
    "C4 SEDAN",
    "C5 AIRCROSS",
    "C5 CROSSTOURER",
    "C5 ESTATE",
    "C5 LIFTBACK",
    "C5 SEDAN",
    "C5 X",
    "C6",
    "C8",
    "CX",
    "CX BREAK",
    "DS",
    "DS3",
    "DS4",
    "DS5",
    "DYANE",
    "E-MEHARI",
    "EVASION",
    "GSA",
    "GRAND C4 PICASSO",
    "LNA",
    "NEMO",
    "SM",
    "SAXO 3 DOORS",
    "SAXO 5 DOORS",
    "TRACTION",
    "VISA",
    "VISA DECOUVRABLE",
    "XM",
    "XM BREAK",
    "XANTIA",
    "XANTIA BREAK",
    "XSARA",
    "XSARA BREAK",
    "XSARA COUPE",
    "XSARA PICASSO",
    "ZX 3 DOORS",
    "ZX 5 DOORS",
    "ZX BREAK",
  ],
  "CUPRA": [
    "ATECA",
    "BORN",
    "FORMENTOR",
    "LEON",
    "LEON SPORTSTOURER",
    "TAVASCAN",
  ],
  "DACIA": [
    "1100",
    "1300",
    "1300 BREAK",
    "1310",
    "1310 BREAK",
    "1310/1410 SPORT",
    "1320",
    "1325",
    "500",
    "DOKKER",
    "DOKKER VAN",
    "DUSTER",
    "DUSTER PICK-UP",
    "JOGGER",
    "LODGY",
    "LOGAN",
    "LOGAN MCV",
    "LOGAN MCV STEPWAY",
    "LOGAN PICK-UP",
    "LOGAN VAN",
    "NOVA",
    "SANDERO",
    "SANDERO STEPWAY",
    "SOLENZA",
    "SPRING",
    "SUPERNOVA",
  ],
  "DAEWOO": [
    "CIELO",
    "CIELO HATCHBACK 3 DOORS",
    "CIELO HATCHBACK 5 DOORS",
    "DAMAS II",
    "ESPERO",
    "G2X",
    "GENTRA",
    "LACETTI",
    "LACETTI 5 DOORS",
    "LACETTI WAGON",
    "LANOS",
    "LANOS HATCHBACK 3 DOORS",
    "LANOS HATCHBACK 5 DOORS",
    "LEGANZA",
    "MAGNUS",
    "MATIZ",
    "NUBIRA",
    "NUBIRA ESTATE",
    "NUBIRA HATCHBACK",
    "STATESMAN",
    "TACUMA",
    "TICO",
    "TOSCA",
    "WINSTORM",
  ],
  "DAIHATSU": [
    "ALTIS",
    "APPLAUSE",
    "AYLA",
    "COPEN",
    "CUORE",
    "FEROZA HARDTOP",
    "FEROZA SOFTTOP",
    "GRAN MOVE",
    "MATERIA",
    "MOVE",
    "ROCKY HARDTOP",
    "ROCKY WAGON",
    "SIRION",
    "SIRION 2",
    "TERIOS",
    "TREVIS",
    "VALERA",
  ],
  "DATSUN": [
    "GO",
    "GO+",
    "MI-DO",
    "ON-DO",
  ],
  "DELOREAN": [
    "DMC-12",
  ],
  "DODGE": [
    "ARIES COUPE",
    "AVENGER",
    "CALIBER",
    "CALIBER SRT4",
    "CARAVAN",
    "CHALLENGER",
    "CHALLENGER SRT",
    "CHARGER",
    "CHARGER SRT",
    "DAKOTA",
    "DAKOTA CLUB CAB",
    "DAKOTA QUAD CAB",
    "DART",
    "DURANGO",
    "DURANGO SRT",
    "HORNET",
    "JOURNEY",
    "MAGNUM",
    "MAGNUM SRT8",
    "NEON",
    "NITRO",
    "POLARA",
    "RAM",
    "STRATUS",
    "STRATUS COUPE",
    "VIPER",
  ],
  "DONKERVOORT": [
    "D8",
  ],
  "DR MOTOR": [
    "DR CITYCROSS",
    "DR1",
    "DR2",
    "DR5",
  ],
  "DS AUTOMOBILES": [
    "DS 3",
    "DS 3 CABRIO",
    "DS 3 CROSSBACK",
    "DS 4",
    "DS 5",
    "DS 5LS",
    "DS 7",
    "DS 9",
  ],
  "EAGLE": [
    "PREMIER",
    "SUMMIT",
    "SUMMIT WAGON",
    "TALON",
  ],
  "FERRARI": [
    "125/159 S",
    "12CILINDRI",
    "12CILINDRI SPIDER",
    "166 SPIDER CORSA",
    "166 SPORT",
    "195",
    "212",
    "250",
    "275",
    "288 GTO/F40/F50/ENZO/LAFERRARI",
    "296 GTB",
    "296 GTS",
    "308 GTB/GTS",
    "328 GTB/GTS",
    "348",
    "348 SPIDER",
    "360 CHALLENGE STRADALE",
    "360 MODENA",
    "360 SPIDER",
    "365",
    "365GT4 BB/ 512BB/ 512 BBI",
    "400",
    "456 GT",
    "458 ITALIA",
    "458 SPECIALE",
    "458 SPECIALE A",
    "458 SPIDER",
    "488 GTB",
    "488 PISTA",
    "488 SPIDER",
    "550 BARCHETTA/575M SUPERAMERICA",
    "550/575M MARANELLO",
    "599",
    "612 SCAGLIETTI",
    "812",
    "CALIFORNIA T",
    "DAYTONA",
    "DINO",
    "F12 BERLINETTA",
    "F12 TRS",
    "F12TDF",
    "F149 CALIFORNIA",
    "F355",
    "F355 SPIDER",
    "F430",
    "F430 SPIDER",
    "F60 AMERICA",
    "F8",
    "FF",
    "FXX",
    "GTC4LUSSO",
    "GTC4LUSSO T",
    "LAFERRARI",
    "MONDIAL",
    "MONDIAL CABRIOLET",
    "MONZA",
    "PORTOFINO",
    "PUROSANGUE",
    "ROMA",
    "ROMA CONVERTIBLE",
    "SF90",
    "SCUDERIA SPIDER",
    "TESTAROSSA/512 TR/512M",
  ],
  "FIAT": [
    "1100 D",
    "1100 D STATION WAGON",
    "1100 E",
    "1100 S",
    "1100 TV SPIDER",
    "12 HP",
    "12-15 HP ZERO",
    "1200",
    "1200 SPIDER",
    "124 COUPE",
    "124 FAMILIALE",
    "124 SALOON",
    "124 SPIDER",
    "125",
    "126",
    "127",
    "127 PANORAMA",
    "128 COUPE",
    "128 SALOON",
    "130 COUPE",
    "130 LIMOUSINE",
    "131 4 DOORS",
    "132",
    "1400",
    "1400 CABRIOLET",
    "15-25 HP BREVETTI TIPO 2",
    "1500",
    "16-20 HP",
    "1800 / 2100",
    "2300 COUPE",
    "2300 SALOON",
    "2300 STATION WAGON",
    "2800",
    "3 1/2 HP",
    "500",
    "500 3+1",
    "500 ABARTH",
    "500 K / GIARDINIERA",
    "500L",
    "500L LIVING",
    "500L TREKKING",
    "500L URBAN",
    "500X",
    "500E",
    "501",
    "501 S",
    "502",
    "503 TORPEDO",
    "505",
    "507",
    "507 TOURING",
    "509",
    "509 S",
    "514",
    "514 SPIDER",
    "519 BERLINA",
    "519 COUPE",
    "519 S",
    "520 SUPERFIAT",
    "521",
    "522 C",
    "524 C",
    "525",
    "527",
    "600",
    "600 D",
    "600 MULTIPLA",
    "850",
    "850 COUPE",
    "850 SPIDER",
    "8V",
    "ALBEA / SIENA",
    "ARGENTA",
    "ARGO",
    "BARCHETTA",
    "BRAVA",
    "BRAVO",
    "BREVETTI",
    "CAMPAGNOLA",
    "CINQUECENTO",
    "COUPE",
    "CROMA",
    "DINO COUPE",
    "DINO SPIDER",
    "DOBLO",
    "FREEMONT",
    "FULLBACK",
    "GRANDE PANDA",
    "GRANDE PUNTO / PUNTO EVO 3 DOORS",
    "GRANDE PUNTO / PUNTO EVO 5 DOORS",
    "IDEA",
    "LINEA",
    "MAREA",
    "MAREA WEEKEND",
    "MILLE",
    "MULTIPLA",
    "PALIO",
    "PALIO WEEKEND",
    "PANDA",
    "PANDA 4X4",
    "PANDA CITY CROSS",
    "PANDA CROSS",
    "PUNTO 3 DOORS",
    "PUNTO 5 DOORS",
    "PUNTO CABRIO",
    "QUBO",
    "REGATA",
    "REGATA WEEKEND",
    "RITMO",
    "SEDICI",
    "SEICENTO",
    "STILO 3 DOORS",
    "STILO 5 DOORS",
    "STILO MULTI WAGON",
    "TEMPRA",
    "TEMPRA SW",
    "TIPO",
    "TIPO 3 DOORS",
    "TIPO 5 DOORS",
    "TIPO CROSS",
    "TIPO STATION WAGON",
    "TOPOLINO",
    "ULYSSE",
    "UNO",
    "UNO 3 DOORS",
    "UNO 5 DOORS",
    "VIAGGIO",
    "X1/9",
  ],
  "FISKER": [
    "KARMA",
    "OCEAN",
  ],
  "FORD": [
    "ANGLIA 100E",
    "ANGLIA 105E",
    "B-MAX",
    "BRONCO",
    "C-MAX",
    "CAPRI",
    "CONSUL",
    "CONTOUR/MONDEO",
    "CORSAIR",
    "CORTINA",
    "COUGAR",
    "CRESTLINE",
    "CRESTLINER",
    "CROWN VICTORIA",
    "DELUXE",
    "E-TOURNEO",
    "ECOSPORT",
    "ECONOVAN",
    "EDGE",
    "EDGE ST",
    "ESCAPE",
    "ESCORT 3 DOORS",
    "ESCORT 4 DOORS",
    "ESCORT 5 DOORS",
    "ESCORT CABRIO",
    "ESCORT CLIPPER",
    "ESCORT WAGON",
    "EVEREST",
    "EXCURSION",
    "EXPEDITION",
    "EXPLORER",
    "EXPLORER ELECTRIC",
    "EXPLORER SPORT",
    "EXPLORER SPORT TRAC",
    "F-150 RAPTOR",
    "F-150 REGULAR CAB",
    "F-150 SUPER CAB",
    "F-150 SUPER CREW",
    "FIESTA 3 DOORS",
    "FIESTA 5 DOORS",
    "FIESTA ST",
    "FIESTA SEDAN",
    "FIGO",
    "FIVE HUNDRED",
    "FLEX",
    "FOCUS 3 DOORS",
    "FOCUS 5 DOORS",
    "FOCUS CC",
    "FOCUS RS",
    "FOCUS ST 5 DOORS",
    "FOCUS ST WAGON",
    "FOCUS SEDAN",
    "FOCUS US",
    "FOCUS WAGON",
    "FREESTAR",
    "FREESTYLE",
    "FUSION EUROPEAN",
    "FUSION NORTH AMERICAN",
    "GT",
    "GALAXY",
    "GRAND C-MAX",
    "KA",
    "KA+",
    "KA+ ACTIVE",
    "KUGA",
    "MAVERICK",
    "MAVERICK LWB",
    "MAVERICK SWB",
    "MODEL A",
    "MODEL T",
    "MONDEO HATCHBACK",
    "MONDEO SEDAN",
    "MONDEO WAGON",
    "MUSTANG",
    "MUSTANG CONVERTIBLE",
    "MUSTANG MACH-E",
    "MUSTANG MACH 1",
    "ORION",
    "PINTO",
    "PROBE",
    "PUMA",
    "PUMA ST",
    "RANGER DOUBLE CAB",
    "RANGER REGULAR CAB",
    "RANGER SUPER CAB",
    "RANGER TREMOR",
    "RANGER WILDTRAK",
    "RAPTOR RANGER",
    "S-MAX",
    "SCORPIO SEDAN",
    "SCORPIO WAGON",
    "SIERRA 3 DOORS",
    "SIERRA 5 DOORS",
    "SIERRA SEDAN",
    "SPORTKA",
    "STREETKA",
    "SUPER DUTY",
    "TAUNUS",
    "TAUNUS CABRIO",
    "TAURUS",
    "TAURUS SHO",
    "TAURUS WAGON",
    "TAURUS X",
    "TERRITORY",
    "THUNDERBIRD",
    "TOURNEO",
    "TRANSIT CONNECT WAGON",
    "TRANSIT CUSTOM",
    "WILDTRAK",
    "WINDSTAR",
    "ZODIAC",
  ],
  "FSO": [
    "125",
    "POLONEZ",
    "POLONEZ ATU",
    "POLONEZ CARO",
    "POLONEZ KOMBI",
    "PRIMA",
  ],
  "GEELY": [
    "CK",
    "EMGRAND EC7",
    "GALAXY",
    "LC",
    "MK",
  ],
  "GENESIS": [
    "G70",
    "G70 SHOOTING BRAKE",
    "G80",
    "G90",
    "GV60",
    "GV70",
    "GV80",
    "GV80 COUPE",
  ],
  "GMC": [
    "ACADIA",
    "CANYON CREW CAB",
    "CANYON DOUBLE CAB",
    "CANYON REGULAR CAB",
    "ENVOY",
    "ENVOY XL",
    "ENVOY XUV",
    "HUMMER EV",
    "HUMMER EV SUV",
    "JIMMY 3 DOORS",
    "JIMMY 5 DOORS",
    "SAFARI",
    "SAVANA",
    "SIERRA",
    "SIERRA 2500HD",
    "SIERRA 3500HD",
    "TERRAIN",
    "YUKON",
    "YUKON XL",
  ],
  "GORDON MURRAY AUTOMOTIVE": [
    "T.33",
    "T.50",
  ],
  "GTA MOTOR": [
    "SPANO",
  ],
  "HINDUSTAN": [
    "AMBASSADOR",
    "PUSHPAK/TREKKER",
    "RTV/RANGER",
  ],
  "HOLDEN": [
    "48-215",
    "ADVENTRA",
    "ASTRA 3 DOORS",
    "ASTRA 5 DOORS",
    "ASTRA CARAVAN",
    "ASTRA TWINTOP",
    "BARINA 3 DOORS",
    "BARINA 5 DOORS",
    "BARINA RS",
    "BARINA SEDAN",
    "BARINA SPARK",
    "CAPRICE/STATESMAN",
    "CAPTIVA",
    "CAPTIVA MAXX",
    "COMBO",
    "COMMODORE SEDAN",
    "COMMODORE WAGON",
    "CREWMAN",
    "CRUZE MK I",
    "CRUZE MK II",
    "DROVER",
    "DROVER DELUXE",
    "EJ WAGON",
    "EPICA",
    "FE",
    "FJ",
    "FRONTERA MX",
    "HJ",
    "HZ",
    "JACKAROO",
    "MALIBU",
    "MONARO",
    "RODEO",
    "STATESMAN",
    "TIGRA",
    "TRAX",
    "UTE",
    "VECTRA LIFTBACK",
    "VECTRA SEDAN",
    "ZAFIRA",
  ],
  "HONDA": [
    " CLARITY",
    "1300 COUPE",
    "1300 SEDAN",
    "ACCORD",
    "ACCORD 3 DOORS",
    "ACCORD COUPE",
    "ACCORD CROSSTOUR",
    "ACCORD EURO",
    "ACCORD TOURER",
    "ACCORD TYPE R",
    "AIRWAVE",
    "AVANCIER",
    "BEAT",
    "CR-V",
    "CR-Z",
    "CRX DEL SOL",
    "CIVIC 3 DOORS",
    "CIVIC 5 DOORS",
    "CIVIC AERO DECK",
    "CIVIC CRX",
    "CIVIC COUPE",
    "CIVIC SEDAN",
    "CIVIC SEDAN US",
    "CIVIC SHUTTLE",
    "CIVIC TOURER",
    "CIVIC TYPE-R",
    "CONCERTO",
    "ELEMENT",
    "FR-V / EDIX",
    "FIT EV",
    "HR-V 3 DOORS",
    "HR-V 5 DOORS",
    "INSIGHT",
    "JAZZ / CITY",
    "JAZZ / FIT",
    "L700",
    "LEGEND COUPE",
    "LEGEND SEDAN",
    "LOGO / FIT",
    "MDX",
    "MOBILIO",
    "N360",
    "N600",
    "NSX",
    "ODYSSEY",
    "PASSPORT",
    "PILOT",
    "PRELUDE",
    "PROLOGUE",
    "RIDGELINE",
    "S2000",
    "S500",
    "S600",
    "S660",
    "S800",
    "S800C",
    "SHUTTLE",
    "STREAM",
    "THAT'S",
    "ZR-V",
    "E",
    "E:NY1",
  ],
  "HUMMER": [
    "H1 2 DOOR HARDTOP",
    "H1 4 DOOR HARDTOP",
    "H1 4 DOOR OPENTOP",
    "H1 4 DOOR WAGON",
    "H2",
    "H2 SUT",
    "H3",
    "H3 ALPHA",
  ],
  "HYUNDAI": [
    "ACCENT 3 DOORS",
    "ACCENT 5 DOORS",
    "ACCENT SEDAN",
    "ATOS",
    "ATOS MULTI",
    "ATOS SPIRIT",
    "BAYON",
    "COUPE / TIBURON",
    "ELANTRA 5 DOORS",
    "ELANTRA COUPE",
    "ELANTRA GT",
    "ELANTRA N",
    "ELANTRA SEDAN",
    "ELANTRA TOURING",
    "EQUUS",
    "EXCEL 3 DOORS",
    "EXCEL 5 DOORS",
    "EXCEL SEDAN",
    "GENESIS",
    "GENESIS COUPE",
    "GETZ 3 DOORS",
    "GETZ 5 DOORS",
    "GRANDEUR / AZERA",
    "IONIQ",
    "IONIQ 5",
    "IONIQ 6",
    "KONA",
    "KONA ELECTRIC",
    "KONA N",
    "LANTRA",
    "LANTRA WAGON",
    "MATRIX",
    "MISTRA",
    "NEXO",
    "PALISADE",
    "PONY 3 DOORS",
    "PONY 5 DOORS",
    "SANTA CRUZ",
    "SANTA FE",
    "SATELLITE",
    "SCOUPE",
    "SONATA",
    "SONATA HYBRID",
    "STARIA",
    "TERRACAN",
    "TRAJET",
    "VELOSTER",
    "VENUE",
    "XG",
    "I10",
    "I20",
    "I20 ACTIVE",
    "I20 COUPE",
    "I20 N",
    "I30",
    "I30 COUPE",
    "I30 ESTATE",
    "I30 FASTBACK",
    "I30 N",
    "I40",
    "I40 WAGON",
    "I800 / H-1",
    "IX20",
    "IX35 / TUCSON",
    "IX55 / VERACRUZ",
  ],
  "INEOS": [
    "GRENADIER",
  ],
  "INFINITI": [
    "EX",
    "FX",
    "G CONVERTIBLE",
    "G COUPE",
    "G SEDAN",
    "G20",
    "G35",
    "G35 COUPE",
    "I",
    "J",
    "JX",
    "M CONVERTIBLE",
    "M COUPE",
    "M SEDAN",
    "Q",
    "Q40",
    "Q50",
    "Q60",
    "Q60 CONVERTIBLE",
    "Q70",
    "QX",
    "QX30",
    "QX50",
    "QX55",
    "QX60",
    "QX70",
    "QX80",
  ],
  "ISUZU": [
    "117 COUPE",
    "AMIGO 3 DOORS",
    "AMIGO CABRIO",
    "ASCENDER",
    "AXIOM",
    "HOMBRE CREW CAB",
    "MU-7",
    "RODEO / D-MAX",
    "TROOPER 3 DOORS",
    "TROOPER 5 DOORS",
    "I-SERIES",
  ],
  "JAGUAR": [
    "E-PACE",
    "F-PACE",
    "F-PACE SVR",
    "F-TYPE CONVERTIBLE",
    "F-TYPE COUPE",
    "F-TYPE SVR",
    "F-TYPE SVR COUPE",
    "I-PACE",
    "S-TYPE",
    "S-TYPE R",
    "X-TYPE",
    "X-TYPE ESTATE",
    "XE",
    "XE SV",
    "XF",
    "XF SPORTBRAKE",
    "XFR",
    "XJ",
    "XJ220",
    "XJR",
    "XK",
    "XK CONVERTIBLE",
    "XKR",
    "XKR CONVERTIBLE",
  ],
  "JEEP": [
    "AVENGER",
    "CHEROKEE",
    "CHEROKEE/LIBERTY",
    "COMMANDER",
    "COMPASS",
    "GLADIATOR",
    "GRAND CHEROKEE",
    "PATRIOT",
    "RENEGADE",
    "WAGONEER",
    "WRANGLER",
    "WRANGLER RUBICON",
    "WRANGLER UNLIMITED",
  ],
  "KARMA": [
    "REVERO GT",
    "REVERO GTS",
  ],
  "KIA": [
    "BORREGO / MOHAVE",
    "CARENS",
    "CARNIVAL / SEDONA",
    "CEED",
    "CERATO / SPECTRA",
    "CERATO/FORTE",
    "EV3",
    "EV5",
    "EV6",
    "EV9",
    "FORTE",
    "FORTE 5 DOOR",
    "FORTE KOUP",
    "JOICE",
    "K4",
    "K5",
    "K7 / CADENZA",
    "K9",
    "NIRO",
    "OPIRUS / AMANTI",
    "OPTIMA / MAGENTIS",
    "OPTIMA SPORTSWAGON",
    "PICANTO",
    "PICANTO X-LINE",
    "PRO CEE'D",
    "RIO HATCHBACK",
    "RIO SEDAN",
    "RONDO",
    "SELTOS",
    "SHUMA",
    "SORENTO",
    "SOUL",
    "SPORTAGE",
    "STINGER",
    "STONIC",
    "STONIC GT-LINE",
    "TELLURIDE",
    "VENGA",
    "XCEED",
    "CEE'D",
    "CEE'D SW",
    "PRO_CEE�D GT",
  ],
  "KOENIGSEGG": [
    "AGERA",
    "CC8S",
    "CCR",
    "CCX",
    "CCXR",
    "GEMERA",
    "JESKO",
    "ONE:1",
    "REGERA",
  ],
  "KTM": [
    "X-BOW",
  ],
  "LADA": [
    "110",
    "111",
    "112",
    "KALINA HATCHBACK",
    "KALINA SEDAN",
    "NIVA",
    "NOVA",
    "NOVA COMBI",
    "PRIORA",
    "SAMARA 3 DOORS",
    "SAMARA 5 DOORS",
    "SAMARA SEDAN",
  ],
  "LAMBORGHINI": [
    "350 GT/ 400 GT",
    "350 GTS",
    "AVENTADOR",
    "AVENTADOR ROADSTER",
    "CENTENARIO",
    "CENTENARIO ROADSTER",
    "COUNTACH",
    "DIABLO",
    "DIABLO ROADSTER",
    "ESPADA",
    "GALLARDO",
    "GALLARDO SPYDER",
    "HURACAN",
    "HURACAN SPYDER",
    "ISLERO",
    "JALPA",
    "JARAMA",
    "LM 002",
    "MIURA",
    "MURCIELAGO",
    "MURCIELAGO ROADSTER",
    "REVENTON",
    "REVUELTO",
    "SIAN",
    "SIAN ROADSTER",
    "SILHOUETTE",
    "URRACO",
    "URUS",
    "VENENO",
    "VENENO ROADSTER",
  ],
  "LANCIA": [
    "2000 COUPE",
    "A112",
    "A112 ABARTH",
    "ALPHA",
    "APRILIA",
    "ARDEA",
    "ARTENA",
    "ASTURA",
    "AUGUSTA",
    "BETA",
    "BETA COUPE",
    "BETA MONTECARLO",
    "BETA SPIDER",
    "DEDRA",
    "DEDRA STATION WAGON",
    "DELTA",
    "DELTA HPE",
    "DILAMBDA",
    "FLAMINIA COUPE",
    "FLAMINIA SEDAN",
    "FLAVIA CONVERTIBLE",
    "FLAVIA SEDAN",
    "FULVIA BERLINA",
    "FULVIA COUPE",
    "GAMMA",
    "GAMMA COUPE",
    "KAPPA",
    "KAPPA COUPE",
    "KAPPA SW",
    "LAMBDA",
    "LYBRA",
    "LYBRA SW",
    "MUSA",
    "PHEDRA",
    "PRISMA",
    "STRATOS",
    "THEMA",
    "THESIS",
    "THETA",
    "TREVI",
    "VOYAGER",
    "YPSILON",
    "ZETA",
  ],
  "LAND ROVER": [
    "DEFENDER 110",
    "DEFENDER 130",
    "DEFENDER 90",
    "DISCOVERY",
    "DISCOVERY SVX",
    "DISCOVERY SPORT",
    "FREELANDER",
    "RANGE ROVER",
    "RANGE ROVER 3 DOORS",
    "RANGE ROVER EVOQUE",
    "RANGE ROVER EVOQUE CONVERTIBLE",
    "RANGE ROVER L",
    "RANGE ROVER PHEV",
    "RANGE ROVER SPORT",
    "RANGE ROVER SPORT PHEV",
    "RANGE ROVER SPORT SVR",
    "RANGE ROVER VELAR",
  ],
  "LEXUS": [
    "CT",
    "ES",
    "GS",
    "GS F",
    "GX",
    "HS",
    "IS",
    "LBX",
    "LC",
    "LFA",
    "LM",
    "LS",
    "LX",
    "NX",
    "RC",
    "RC F",
    "RX",
    "RZ",
    "SC",
    "TX",
    "UX",
  ],
  "LIGHTYEAR": [
    "LIGHTYEAR 0",
    "LIGHTYEAR 2",
  ],
  "LINCOLN": [
    "AVIATOR",
    "CONTINENTAL",
    "CORSAIR",
    "LS",
    "MKC",
    "MKS",
    "MKT",
    "MKX",
    "MKZ",
    "MARK LT",
    "NAUTILUS",
    "NAVIGATOR",
    "NAVIGATOR L",
    "TOWN CAR",
    "ZEPHYR",
    "ZEPHYR FASTBACK",
  ],
  "LOTUS": [
    "2 ELEVEN",
    "3 ELEVEN",
    "ELAN",
    "ELETRE",
    "ELISE",
    "ELITE",
    "EMEYA",
    "EMIRA",
    "ESPRIT",
    "EUROPA",
    "EVIJA",
    "EVORA",
    "EXCEL",
    "EXIGE",
  ],
  "LUCID MOTORS": [
    "AIR",
    "GRAVITY",
  ],
  "MAHINDRA": [
    "BOLERO",
    "SCORPIO / GOA",
    "THAR",
    "VERITO",
  ],
  "MARUSSIA": [
    "B1",
    "B2",
  ],
  "MARUTI SUZUKI": [
    "800",
    "ALTO",
    "BALENO",
    "CIAZ",
    "ESTEEM",
    "GIPSY",
    "SWIFT",
    "WAGON R",
    "ZEN",
  ],
  "MASERATI": [
    "BORA",
    "COUPE",
    "GHIBLI",
    "GRANCABRIO",
    "GRANSPORT",
    "GRANTURISMO",
    "GRECALE",
    "GRECALE TROFEO",
    "INDY",
    "LEVANTE",
    "MC 12",
    "MC20",
    "MERAK",
    "QUATTROPORTE",
    "QUATTROPORTE SPORT GT S",
    "SPYDER",
  ],
  "MAYBACH": [
    "57",
    "62",
    "LANDAULET",
    "TYP 12",
    "TYP SW 35, SW 38 AND SW 42",
    "TYP W1, W2, W3, W5 AND W5 SG",
    "TYP W6, W6 DSG AND DSH",
    "TYP ZEPPELIN",
  ],
  "MAZDA": [
    "121",
    "2 / DEMIO",
    "2 / DEMIO - 3 DOORS",
    "2 / DEMIO - SEDAN",
    "3 / AXELA HATCHBACK",
    "3 / AXELA SEDAN",
    "3 MPS / MAZDASPEED 3",
    "323 HATCHBACK",
    "323 SEDAN",
    "323 STATION WAGON",
    "5 / PREMACY",
    "6 / ATENZA HATCHBACK",
    "6 / ATENZA SEDAN",
    "6 / ATENZA WAGON",
    "626 HATCHBACK",
    "626 SEDAN",
    "626 STATION WAGON",
    "B SERIES / BRAVO DUAL CAB",
    "B SERIES / BRAVO FREESTYLE CAB",
    "BT-50",
    "BIANTE",
    "CX-3",
    "CX-30",
    "CX-5",
    "CX-50",
    "CX-60",
    "CX-7",
    "CX-70",
    "CX-8",
    "CX-80",
    "CX-9",
    "CX-90",
    "FLAIR",
    "FLAIRWAGON",
    "MX-3",
    "MX-30",
    "MX-5 / MIATA",
    "MX-6",
    "RX-7",
    "RX-8",
    "TRIBUTE",
    "VERISA",
    "XEDOS 6",
    "XEDOS 9",
  ],
  "MCLAREN": [
    "12C GT SPRINT",
    "540C",
    "570GT",
    "570S",
    "570S SPIDER",
    "600LT",
    "620R",
    "650S",
    "650S SPIDER",
    "675LT",
    "675LT SPIDER",
    "720S",
    "750S",
    "765LT",
    "ARTURA",
    "ELVA",
    "F1",
    "F1 GT",
    "F1 LM",
    "GT",
    "GTS",
    "MP4-12C",
    "MP4-12C SPIDER",
    "P1",
    "SENNA",
    "SPEEDTAIL",
  ],
  "MERCEDES BENZ": [
    "A-CLASS SEDAN",
    "A-KLASSE",
    "A-KLASSE AMG",
    "A-KLASSE COUPE",
    "A-KLASSE SALOON",
    "B-KLASSE",
    "C-CLASS CABRIOLET",
    "C-KLASSE AMG",
    "C-KLASSE ALL-TERRAIN",
    "C-KLASSE COUPE",
    "C-KLASSE COUPE AMG",
    "C-KLASSE SPORTCOUPE AMG",
    "C-KLASSE SPORTCOUPE/CLC",
    "C-KLASSE T-MODELL",
    "C-KLASSE AND PREDECESSORS",
    "CL AMG",
    "CL-KLASSE AND PREDECESSORS",
    "CLA 45",
    "CLA KLASSE",
    "CLA SHOOTING BRAKE",
    "CLE CABRIOLET",
    "CLE COUPE",
    "CLK AMG",
    "CLK AMG CABRIO",
    "CLK GTR",
    "CLS AMG",
    "CLS SHOOTING BRAKE",
    "CLS SHOOTING BRAKE AMG",
    "CLS-KLASSE",
    "CITAN",
    "E-CLASS T-MODELL ALL-TERRAIN",
    "E-KLASSE AMG",
    "E-KLASSE CABRIOLET AND PREDECESSORS",
    "E-KLASSE COUPE AND PREDECESSORS",
    "E-KLASSE T-MODELL",
    "E-KLASSE T-MODELL AMG",
    "E-KLASSE AND PREDECESSORS",
    "EQA",
    "EQB",
    "EQC",
    "EQE",
    "EQE SUV",
    "EQS",
    "EQS SUV",
    "EQS SUV MAYBACH",
    "EQT",
    "EQV",
    "G-KLASSE",
    "G-KLASSE AMG",
    "G-KLASSE CABRIOLET",
    "G-KLASSE KURZ",
    "G1, G4, G5, L 1500 A, 170 VL, 170 VK",
    "GL-KLASSE",
    "GL-KLASSE AMG",
    "GLA",
    "GLB",
    "GLC CLASS",
    "GLC CLASS COUPE",
    "GLE-CLASS",
    "GLE-CLASS COUPE",
    "GLK-KLASSE",
    "GLS MAYBACH",
    "GLS-CLASS",
    "LAUNDALET",
    "M-KLASSE",
    "M-KLASSE AMG",
    "MAYBACH EQS SUV",
    "PULLMAN",
    "R-KLASSE",
    "R-KLASSE AMG",
    "R-KLASSE LANG",
    "S-CLASS CABRIOLET",
    "S-CLASS COUPE AMG",
    "S-CLASS MAYBACH",
    "S-KLASSE AMG",
    "S-KLASSE COUPE",
    "S-KLASSE AND PREDECESSORS",
    "SL AMG",
    "SL-KLASSE",
    "SLC-CLASS",
    "SLK AMG",
    "SLK-KLASSE",
    "SLR MCLAREN",
    "SLS AMG",
    "T-CLASS",
    "TYP 12/55 - 14/60",
    "TYP 130, 150 AND 170 H",
    "TYP 170/170 V",
    "TYP 200",
    "TYP 230, 260 D",
    "TYP 290",
    "TYP 320",
    "TYP 380",
    "TYP 500 K/ 540 K",
    "TYP 770",
    "TYP 8/38",
    "TYP MANNHEIM",
    "TYP NURBURG",
    "TYP S, SS, SSK, SSKL",
    "TYP STUTTGART",
    "V-CLASS AND PREDECESSORS",
    "VANEO",
    "VIANO",
    "VITO",
    "X-CLASS",
  ],
  "MERCEDES-AMG": [
    "A-CLASS",
    "C-CLASS",
    "C-CLASS COUPE",
    "C-CLASS CABRIOLET",
    "C-CLASS T-MODELL",
    "C-CLASS WAGON",
    "CLA SHOOTING BRAKE",
    "CLA-CLASS",
    "CLE CABRIOLET",
    "CLE COUPE",
    "CLS-CLASS",
    "E-CLASS",
    "E-CLASS CABRIOLET",
    "E-CLASS COUPE",
    "E-CLASS ESTATE",
    "EQE",
    "EQE SUV",
    "EQS",
    "G 63",
    "GLA",
    "GLB",
    "GLC  COUPE",
    "GLC-CLASS",
    "GLE",
    "GLE  COUPE",
    "GLS- CLASS",
    "GT 4-DOOR COUPE",
    "GT COUPE",
    "GT ROADSTER",
    "ONE",
    "S-CLASS",
    "S-CLASS CABRIOLET",
    "S-CLASS COUPE",
    "SL-CLASS",
    "SLC",
  ],
  "MERCURY": [
    "COUGAR",
    "GRAND MARQUIS",
    "MARAUDER",
    "MARINER",
    "MILAN",
    "MONTEGO",
    "MONTEREY",
    "MOUNTAINEER",
    "SABLE",
    "VILLAGER",
  ],
  "MG": [
    "F/ TF",
    "GS",
    "HS",
    "MG 3",
    "MG 4",
    "MG 5",
    "MG 6",
    "MARVEL R",
    "XPOWER",
    "ZR 3 DOORS",
    "ZR 5 DOORS",
    "ZS",
    "ZS HATCHBACK",
    "ZS SEDAN",
    "ZT",
    "ZT-T",
  ],
  "MINI": [
    "ACEMAN",
    "CLASSIC",
    "CLUBMAN",
    "CLUBVAN",
    "CONVERTIBLE",
    "COUNTRYMAN",
    "COUPE",
    "HATCH",
    "PACEMAN",
    "ROADSTER",
  ],
  "MITSUBISHI": [
    "3000 GT",
    "ASX / RVR / OUTLANDER SPORT",
    "ATTRAGE",
    "CARISMA SEDAN",
    "COLT 3 DOORS",
    "COLT 5 DOORS",
    "COLT CZC",
    "ECLIPSE",
    "ECLIPSE CROSS",
    "ECLIPSE SPYDER",
    "ENDEAVOR",
    "GALANT",
    "GALANT STATION WAGON",
    "GRANDIS",
    "L 200",
    "L300",
    "LANCER",
    "LANCER COMBI",
    "LANCER EVOLUTION",
    "LANCER HATCHBACK",
    "MIRAGE",
    "MIRAGE G4",
    "OUTLANDER / AIRTREK",
    "PAJERO 3 DOORS",
    "PAJERO 5 DOORS",
    "PAJERO PININ / SHOGUN PININ / MONTERO IO",
    "RAIDER CREW CAB",
    "RAIDER DOUBLE CAB",
    "SIGMA",
    "SPACE RUNNER",
    "SPACE STAR",
    "STARION",
    "I-MIEV",
  ],
  "MORGAN": [
    "3 WHEELER",
    "4/4 2 SEATER",
    "4/4 4 SEATER",
    "AERO 8",
    "AERO COUPE",
    "AERO SUPERSPORTS",
    "AEROMAX",
    "PLUS 4",
    "PLUS 8",
    "PLUS SIX",
    "ROADSTER",
  ],
  "NIO": [
    "EC6",
    "EP9",
    "ES6",
    "ES8",
    "ET7",
  ],
  "NISSAN": [
    "100 NX",
    "200 SX",
    "300 ZX",
    "350Z",
    "350Z ROADSTER",
    "370Z",
    "370Z NISMO",
    "370Z ROADSTER",
    "ALMERA / PULSAR 3 DOORS",
    "ALMERA / PULSAR 5 DOORS",
    "ALMERA / PULSAR SEDAN",
    "ALMERA TINO",
    "ALTIMA",
    "ARIYA",
    "ARMADA",
    "BLUEBIRD HATCHBACK",
    "BLUEBIRD SEDAN",
    "BLUEBIRD TRAVELLER",
    "CUBE",
    "GT-R",
    "GT-R NISMO",
    "GRAND LIVINA",
    "JUKE",
    "JUKE NISMO",
    "KICKS",
    "LEAF",
    "LIBERTY",
    "MAXIMA",
    "MICRA 3 DOORS",
    "MICRA 5 DOORS",
    "MICRA C+C",
    "MURANO",
    "MURANO CROSSCABRIOLET",
    "NP300",
    "NV",
    "NAVARA / FRONTIER DOUBLE CAB",
    "NAVARA / FRONTIER KING CAB",
    "NOTE",
    "PATHFINDER",
    "PATROL LWB",
    "PATROL SWB",
    "PIXO",
    "PLATINA",
    "PRAIRIE",
    "PRIMERA BREAK",
    "PRIMERA HATCHBACK",
    "PRIMERA SEDAN",
    "QASHQAI",
    "QUEST",
    "ROGUE",
    "SAKURA",
    "SENTRA",
    "SERENA",
    "SKYLINE",
    "SUNNY",
    "SUNNY 3 DOORS",
    "SUNNY HATCHBACK",
    "SUNNY SEDAN",
    "SUNNY TRAVELLER",
    "TEANA",
    "TERRANO 3 DOORS",
    "TERRANO 5 DOORS",
    "TIIDA / VERSA",
    "TIIDA / VERSA SEDAN",
    "TITAN CREW CAB",
    "TITAN KING CAB",
    "X-TRAIL",
    "XTERRA",
    "Z",
  ],
  "OLDSMOBILE": [
    "442 CONVERTIBLE",
    "88",
    "ALERO COUPE",
    "ALERO SEDAN",
    "AURORA",
    "BRAVADA",
    "CURVED DASH",
    "CUTLASS",
    "INTRIGUE",
    "SILHOUETTE",
    "TORONADO",
  ],
  "OPEL": [
    "ADAM",
    "ADAM ROCKS",
    "AGILA",
    "AMPERA",
    "ANTARA",
    "ASTRA 3 DOORS",
    "ASTRA 5 DOORS",
    "ASTRA CABRIOLET",
    "ASTRA CARAVAN",
    "ASTRA COUPE",
    "ASTRA GTC",
    "ASTRA OPC",
    "ASTRA SEDAN",
    "ASTRA SPORTS TOURER",
    "ASTRA TWIN TOP / CABRIOLET",
    "CALIBRA",
    "CASCADA",
    "COMBO",
    "CORSA 3 DOORS",
    "CORSA 5 DOORS",
    "CORSA OPC",
    "CROSSLAND",
    "FRONTERA",
    "GT",
    "GRANDLAND",
    "INSIGNIA",
    "INSIGNIA COUNTRY TOURER",
    "INSIGNIA GSI",
    "INSIGNIA OPC",
    "INSIGNIA SPORTS TOURER",
    "INSIGNIA SPORTS TOURER GSI",
    "INSIGNIA SPORTS TOURER OPC",
    "KADETT 3 DOORS",
    "KADETT 5 DOORS",
    "KADETT CABRIOLET",
    "KADETT CARAVAN",
    "KADETT SEDAN",
    "KARL",
    "MANTA",
    "MERIVA",
    "MOKKA",
    "MONTEREY",
    "MONZA",
    "OMEGA CARAVAN",
    "OMEGA SEDAN",
    "REKORD CARAVAN",
    "REKORD SEDAN",
    "ROCKS-E",
    "SENATOR",
    "SIGNUM",
    "SINTRA",
    "SPEEDSTER",
    "TIGRA",
    "VECTRA CARAVAN",
    "VECTRA HATCHBACK",
    "VECTRA OPC",
    "VECTRA SEDAN",
    "ZAFIRA",
  ],
  "PAGANI": [
    "HUAYRA",
    "HUAYRA ROADSTER",
    "IMOLA",
    "UTOPIA",
    "ZONDA CINQUE",
    "ZONDA CINQUE ROADSTER",
    "ZONDA F",
    "ZONDA F ROADSTER",
    "ZONDA ROADSTER",
    "ZONDA S",
  ],
  "PANOZ": [
    "AVEZZANO",
    "ESPERANTE",
    "ESPERANTE GT",
    "ESPERANTE GTLM",
    "ROADSTER",
  ],
  "PERODUA": [
    "ALZA",
    "ARUZ",
    "AXIA",
    "BEZZA",
    "MYVI",
  ],
  "PEUGEOT": [
    "1007",
    "104",
    "106",
    "107 3 DOORS",
    "107 5 DOORS",
    "108",
    "2008",
    "205",
    "206 3 DOORS",
    "206 5 DOORS",
    "206 CC",
    "206 SW",
    "206 SEDAN",
    "206+ 3 DOORS",
    "206+ 5 DOORS",
    "207 3 DOORS",
    "207 5 DOORS",
    "207 CC",
    "207 SW",
    "208 3 DOORS",
    "208 5 DOORS",
    "208 GTI",
    "208 XY",
    "3008",
    "301",
    "306",
    "307 3 DOORS",
    "307 5 DOORS",
    "307 CC",
    "307 SW",
    "307 SEDAN",
    "308 3 DOORS",
    "308 5 DOORS",
    "308 CC",
    "308 SW",
    "4007",
    "4008",
    "405",
    "406",
    "406 BREAK",
    "406 COUPE",
    "407",
    "407 COUPE",
    "407 SW",
    "408 FASTBACK",
    "408 SEDAN",
    "5008",
    "504",
    "505",
    "508",
    "508 RXH",
    "508 SW",
    "604",
    "605",
    "607",
    "806",
    "807",
    "HOGGAR",
    "LANDTREK",
    "PARTNER COMBI",
    "PICK UP",
    "RCZ",
    "RCZ R",
    "RIFTER",
    "TEPEE",
    "TRAVELLER",
    "ION",
  ],
  "PININFARINA": [
    "B95",
    "BATTISTA",
  ],
  "PLYMOUTH": [
    "ACCLAIM",
    "BARRACUDA",
    "BREEZE",
    "LASER",
    "NEON COUPE",
    "NEON SEDAN",
    "VOYAGER",
    "VALIANT",
  ],
  "POLESTAR": [
    "1",
    "2",
    "3",
    "4",
  ],
  "PONTIAC": [
    "AZTEK",
    "BONNEVILLE",
    "FIERO",
    "FIREBIRD",
    "G3",
    "G5",
    "G6",
    "G6 CONVERTIBLE",
    "G6 COUPE",
    "G8",
    "GTO",
    "GRAND AM",
    "GRAND PRIX",
    "MONTANA",
    "SOLSTICE",
    "SUNFIRE CABRIO",
    "SUNFIRE COUPE",
    "SUNFIRE SEDAN",
    "TORRENT",
    "TRANS SPORT",
    "VIBE",
  ],
  "PORSCHE": [
    "718 BOXSTER",
    "718 BOXSTER GTS",
    "718 BOXSTER S",
    "718 CAYMAN",
    "718 CAYMAN GT4",
    "718 CAYMAN GTS",
    "718 CAYMAN S",
    "718 SPYDER",
    "911 CARRERA",
    "911 CARRERA 4",
    "911 CARRERA 4 CABRIOLET",
    "911 CARRERA 4 GTS",
    "911 CARRERA 4 GTS CABRIOLET",
    "911 CARRERA 4S",
    "911 CARRERA 4S CABRIOLET",
    "911 CARRERA CABRIOLET",
    "911 CARRERA GTS",
    "911 CARRERA GTS CABRIOLET",
    "911 CARRERA RS",
    "911 CARRERA S",
    "911 CARRERA S CABRIOLET",
    "911 CARRERA T",
    "911 GT2",
    "911 GT2 RS",
    "911 GT3",
    "911 GT3 RS",
    "911 R",
    "911 SPORT CLASSIC",
    "911 TARGA",
    "911 TARGA 4",
    "911 TARGA 4 GTS",
    "911 TARGA 4S",
    "911 TURBO",
    "911 TURBO CABRIOLET",
    "911 TURBO S",
    "911 TURBO S CABRIOLET",
    "918",
    "928",
    "928 GT",
    "928 GTS",
    "928 S",
    "944",
    "944 S",
    "944 TURBO",
    "959",
    "968",
    "968 CABRIOLET",
    "968 TURBO S",
    "BOXSTER",
    "BOXSTER S",
    "BOXSTER SPYDER",
    "CARRERA GT",
    "CAYENNE",
    "CAYENNE COUPE",
    "CAYENNE DIESEL",
    "CAYENNE GTS",
    "CAYENNE GTS COUPE",
    "CAYENNE S",
    "CAYENNE S DIESEL",
    "CAYENNE S E-HYBRID",
    "CAYENNE S HYBRID",
    "CAYENNE S TRANSSYBERIA",
    "CAYENNE TURBO",
    "CAYENNE TURBO COUPE",
    "CAYENNE TURBO E-HYBRID",
    "CAYENNE TURBO E-HYBRID COUPE",
    "CAYENNE TURBO S",
    "CAYENNE TURBO S E-HYBRID",
    "CAYMAN",
    "CAYMAN R",
    "CAYMAN S",
    "MACAN",
    "MACAN 4 ELECTRIC",
    "MACAN GTS",
    "MACAN S",
    "MACAN S DIESEL",
    "MACAN T",
    "MACAN TURBO",
    "MACAN TURBO ELECTRIC",
    "PANAMERA",
    "PANAMERA 4",
    "PANAMERA 4 E-HYBRID",
    "PANAMERA 4 E-HYBRID SPORT TURISMO",
    "PANAMERA 4 SPORT TURISMO",
    "PANAMERA 4S",
    "PANAMERA 4S DIESEL",
    "PANAMERA 4S DIESEL SPORT TURISMO",
    "PANAMERA 4S E-HYBRID",
    "PANAMERA 4S SPORT TURISMO",
    "PANAMERA DIESEL",
    "PANAMERA GTS",
    "PANAMERA GTS SPORT TURISMO",
    "PANAMERA S",
    "PANAMERA S E-HYBRID",
    "PANAMERA S HYBRID",
    "PANAMERA TURBO",
    "PANAMERA TURBO E HYBRID",
    "PANAMERA TURBO S",
    "PANAMERA TURBO S E-HYBRID",
    "PANAMERA TURBO S E-HYBRID SPORT TURISMO",
    "PANAMERA TURBO S SPORT TURISMO",
    "PANAMERA TURBO SPORT TURISMO",
    "SPEEDSTER",
    "TAYCAN",
    "TAYCAN CROSS TURISMO",
    "TAYCAN GTS",
    "TAYCAN GTS SPORT TURISMO",
    "TAYCAN SPORT TURISMO",
    "TAYCAN TURBO",
  ],
  "PROTON": [
    "ARENA / JUMBUCK",
    "ERTIGA",
    "EXORA",
    "GEN-2",
    "INSPIRA",
    "IRIZ",
    "PERDANA",
    "PERSONA",
    "PREVE",
    "SAGA",
    "SATRIA NEO",
    "SAVVY",
    "SUPRIMA S",
    "WAJA / IMPIAN",
  ],
  "QOROS": [
    "3",
    "5",
  ],
  "RAM TRUCKS": [
    "1500",
    "2500",
    "3500",
  ],
  "RENAULT": [
    "11",
    "12",
    "14",
    "16",
    "18",
    "19",
    "20",
    "21",
    "25",
    "30",
    "4 CV",
    "5",
    "5 ELECTRIC",
    "8",
    "9",
    "ALASKAN",
    "ALPINE",
    "ARKANA",
    "AUSTRAL",
    "AVANTIME",
    "CAPTUR",
    "CITY K-ZE",
    "CLIO 3 DOORS",
    "CLIO 5 DOORS",
    "CLIO ESTATE",
    "CLIO RS",
    "CLIO SYMBOL / THALIA",
    "ESPACE",
    "FLUENCE",
    "FUEGO",
    "GRAND KANGOO",
    "GRAND MODUS",
    "GRAND SCENIC",
    "KADJAR",
    "KANGOO",
    "KARDIAN",
    "KIGER",
    "KOLEOS",
    "KWID",
    "LAGUNA",
    "LAGUNA COUPE",
    "LAGUNA ESTATE",
    "LATITUDE",
    "LOGAN",
    "MEGANE 5 DOORS",
    "MEGANE CABRIOLET",
    "MEGANE COUPE",
    "MEGANE E-TECH",
    "MEGANE ESTATE",
    "MEGANE SEDAN",
    "MODUS",
    "PULSE",
    "RAFALE",
    "SCENIC XMOD",
    "SAFRANE",
    "SANDERO",
    "SCALA",
    "SCENIC",
    "SPIDER",
    "SYMBIOZ",
    "TALISMAN",
    "TALISMAN ESTATE",
    "TRIBER",
    "TWINGO",
    "TWINGO RS",
    "TWIZY",
    "VEL SATIS",
    "WIND",
    "ZOE",
  ],
  "RIMAC": [
    "NEVERA",
  ],
  "RIVIAN": [
    "R1S",
    "R1T",
    "R2",
    "R3",
    "R3X",
  ],
  "ROLLS-ROYCE": [
    "ARCADIA",
    "CAMARGUE",
    "CORNICHE",
    "CULLINAN",
    "DAWN",
    "FLYING SPUR",
    "GHOST",
    "LA ROSE NOIRE",
    "PARK WARD",
    "PHANTOM",
    "SILVER DAWN",
    "SILVER SERAPH",
    "SILVER SHADOW",
    "SILVER SHADOW COUPE",
    "SILVER SPIRIT",
    "SILVER SPUR",
    "SPECTRE",
    "WRAITH",
  ],
  "SAAB": [
    "9-2X",
    "9-3 AERO",
    "9-3 CONVERTIBLE",
    "9-3 COUPE",
    "9-3 SPORT SEDAN",
    "9-3 SPORTCOMBI",
    "9-3X",
    "9-5",
    "9-5 SPORTCOMBI",
    "9-7X",
    "90",
    "900",
    "900 CABRIO",
    "9000",
  ],
  "SALEEN": [
    "S7",
    "S7TT",
  ],
  "SAMSUNG": [
    "SM 3",
    "SM 5",
    "SM 7",
  ],
  "SANTANA": [
    "300 - 350",
    "PS 10 PICKUP",
    "PS 10 PLUS",
    "PS 10 SHORTLINE",
  ],
  "SATURN": [
    "ASTRA",
    "AURA",
    "ION QUAD COUPE",
    "ION SEDAN",
    "OUTLOOK",
    "RELAY",
    "SKY",
    "VUE",
  ],
  "SCION": [
    "FR-S",
    "IA",
    "IM",
    "IQ",
    "TC",
    "XA",
    "XB",
    "XD",
  ],
  "SEAT": [
    "ALHAMBRA",
    "ALTEA",
    "ARONA",
    "AROSA",
    "ATECA",
    "CORDOBA",
    "CORDOBA CUPRA",
    "CORDOBA SX",
    "CORDOBA VARIO",
    "EXEO",
    "EXEO ST",
    "IBIZA",
    "IBIZA 3 DOORS",
    "IBIZA 5 DOORS",
    "IBIZA BOCANEGRA",
    "IBIZA CUPRA",
    "IBIZA FR",
    "IBIZA ST",
    "LEON",
    "LEON CUPRA",
    "LEON CUPRA R",
    "LEON FR / TOPSPORT",
    "LEON SC",
    "LEON ST CUPRA",
    "LEON ST ESTATE",
    "LEON X-PERIENCE",
    "MALAGA",
    "MARBELLA",
    "MII",
    "TARRACO",
    "TOLEDO",
  ],
  "SKODA": [
    "100 SERIES",
    "860",
    "CITIGO",
    "ENYAQ",
    "ENYAQ COUPE",
    "FABIA",
    "FABIA COMBI",
    "FABIA COMBI RS",
    "FABIA RS",
    "FABIA SEDAN",
    "FAVORIT",
    "FAVORIT ESTATE",
    "FELICIA",
    "FELICIA COMBI",
    "KAMIQ",
    "KAROQ",
    "KODIAQ",
    "KUSHAQ",
    "OCTAVIA",
    "OCTAVIA COMBI",
    "OCTAVIA COMBI 4X4",
    "OCTAVIA COMBI RS",
    "OCTAVIA RS",
    "OCTAVIA SCOUT",
    "RAPID",
    "RAPID SPACEBACK",
    "ROOMSTER",
    "SCALA",
    "SLAVIA",
    "SUPERB",
    "SUPERB COMBI / SCOUT",
    "YETI",
  ],
  "SMART": [
    "1",
    "ELECTRIC DRIVE",
    "ROADSTER",
    "ROADSTER BRABUS",
    "ROADSTER COUPE",
    "ROADSTER COUPE BRABUS",
    "CROSSBLADE",
    "FORFOUR",
    "FORFOUR BRABUS",
    "FORTWO",
    "FORTWO BRABUS",
    "FORTWO CABRIO",
    "FORTWO CABRIO BRABUS",
  ],
  "SPYKER": [
    "C12 LATURBIE",
    "C8 DOUBLE 12 S",
    "C8 LAVIOLETTE",
    "C8 PRELIATOR",
    "C8 SPYDER",
  ],
  "SSANGYONG": [
    "ACTYON",
    "CHAIRMAN",
    "KORANDO",
    "KYRON",
    "MUSSO",
    "MUSSO SPORTS",
    "REXTON",
    "RODIUS",
    "TIVOLI",
    "TIVOLI XLV",
  ],
  "SUBARU": [
    "360",
    "ASCENT",
    "BRZ",
    "BAJA",
    "CROSSTREK",
    "EXIGA LIBERTY",
    "FORESTER",
    "IMPREZA",
    "IMPREZA WRX STI",
    "JUSTY",
    "LEGACY",
    "LEGACY WAGON",
    "LEVORG",
    "LIBERTY",
    "MINI JUMBO",
    "OUTBACK",
    "R1",
    "R2",
    "SVX",
    "SOLTERRA",
    "STELLA",
    "TREZIA",
    "TRIBECA",
    "VIVIO",
    "WRX",
    "XV",
  ],
  "SUZUKI": [
    "APV",
    "ACROSS",
    "AERIO / LIANA HATCHBACK",
    "AERIO / LIANA SEDAN",
    "ALTO",
    "BALENO",
    "EQUATOR",
    "ERTIGA",
    "ESCUDO / GRAND VITARA 3 DOORS",
    "ESCUDO / GRAND VITARA 5 DOORS",
    "ESCUDO / VITARA 3 DOORS",
    "FORENZA SEDAN",
    "FORENZA WAGON",
    "IGNIS",
    "JIMNY",
    "KIZASHI",
    "RENO",
    "S-CROSS",
    "SX4 CROSSOVER",
    "SX4 SEDAN",
    "SPLASH",
    "SWACE",
    "SWIFT 3 DOORS",
    "SWIFT 5 DOORS",
    "SWIFT CABRIOLET",
    "SWIFT SEDAN",
    "VERONA",
    "VITARA",
    "WAGON R",
    "X90",
    "XL7",
  ],
  "TATA MOTORS": [
    "ALTROZ",
    "ARIA",
    "HARRIER",
    "INDICA",
    "INDIGO",
    "INDIGO SW",
    "NANO",
    "NEXON",
    "SAFARI",
    "SUMO",
    "TELCOLINE DOUBLE CAB",
  ],
  "TESLA": [
    "CYBERTRUCK",
    "MODEL 3",
    "MODEL S",
    "MODEL X",
    "MODEL Y",
    "ROADSTER",
  ],
  "TOYOTA": [
    "4RUNNER",
    "AGYA",
    "ALPHARD",
    "AQUA",
    "AURION",
    "AURIS 3 DOORS",
    "AURIS 5 DOORS",
    "AURIS TOURING",
    "AVALON",
    "AVENSIS",
    "AVENSIS LIFTBACK",
    "AVENSIS VERSO",
    "AVENSIS WAGON",
    "AYGO 3 DOORS",
    "AYGO 5 DOORS",
    "AYGO X",
    "C-HR",
    "CAMRY",
    "CELICA",
    "CELICA CONVERTIBLE",
    "CENTURY SUV",
    "CENTURY SEDAN",
    "COROLLA",
    "COROLLA (US)",
    "COROLLA 3 DOORS",
    "COROLLA 5 DOORS",
    "COROLLA CROSS",
    "COROLLA CROSS (US)",
    "COROLLA LIFTBACK",
    "COROLLA SEDAN",
    "COROLLA TOURING",
    "COROLLA VERSO",
    "COROLLA WAGON",
    "CROWN",
    "CROWN SUV",
    "ETIOS",
    "ETIOS LIVA",
    "FJ CRUISER",
    "FORTUNER",
    "GR 86",
    "GR COROLLA",
    "GR SUPRA",
    "GR YARIS",
    "GT 86",
    "GRAND HIGHLANDER",
    "HARRIER",
    "HIGHLANDER / KLUGER",
    "HILUX",
    "HILUX DOUBLE CAB",
    "HILUX EXTRA CAB",
    "HILUX SINGLE CAB",
    "INNOVA",
    "LAND CRUISER / PRADO",
    "LAND CRUISER V8 AND PREDECESSORS",
    "MR2",
    "MR2 CABRIOLET",
    "MATRIX",
    "MIRAI",
    "PASEO",
    "PICNIC",
    "PREVIA / ESTIMA",
    "PRIUS",
    "PRIUS C (AQUA)",
    "PRIUS PRIME",
    "PRIUS V/PRIUS+",
    "RAV4 3 DOORS",
    "RAV4 5 DOORS",
    "RUKUS",
    "SEQUOIA",
    "SIENNA",
    "SOLARA CONVERTIBLE",
    "STARLET 3 DOORS",
    "STARLET 5 DOORS",
    "SUPRA",
    "TACOMA",
    "TUNDRA",
    "URBAN CRUISER",
    "VERSO-S",
    "VENZA",
    "VERSO",
    "VIOS",
    "YARIS 3 DOORS",
    "YARIS 5 DOORS",
    "YARIS CROSS",
    "YARIS HATCHBACK",
    "YARIS SEDAN",
    "YARIS TS 3 DOORS",
    "YARIS TS 5 DOORS",
    "YARIS VERSO",
    "BZ",
    "IQ",
  ],
  "TVR": [
    "WEDGE SERIES",
    "CERBERA",
    "CHIMAERA",
    "GRIFFITH",
    "SAGARIS",
    "T350",
    "TAMORA",
    "TUSCAN",
    "TUSCAN R/ T 440R/T 400R/ TYPHON",
    "TUSCAN S",
    "TUSCAN S CONVERTIBLE",
  ],
  "VAUXHALL": [
    "AGILA",
    "ANTARA",
    "ASTRA ESTATE",
    "ASTRA HATCHBACK",
    "ASTRA SPORT HATCH",
    "ASTRA TWIN TOP",
    "ASTRA VXR",
    "CORSA 3 DOORS",
    "CORSA 5 DOORS",
    "CORSA VXR",
    "CROSSLAND X",
    "GRANDLAND",
    "INSIGNIA COUNTRY TOURER",
    "INSIGNIA HATCHBACK",
    "INSIGNIA SEDAN",
    "INSIGNIA SPORTS TOURER",
    "INSIGNIA VXR SEDAN",
    "INSIGNIA VXR SPORTS TOURER",
    "MERIVA",
    "MERIVA VXR",
    "MOKKA",
    "MOKKA X",
    "MONARO",
    "MONARO VXR",
    "SIGNUM",
    "TIGRA TWIN TOP",
    "VX 220",
    "VXR8",
    "VECTRA ESTATE",
    "VECTRA ESTATE VXR",
    "VECTRA HATCHBACK",
    "VECTRA SALOON",
    "VECTRA VXR",
    "VIVA",
    "ZAFIRA",
    "ZAFIRA VXR",
  ],
  "VINFAST": [
    "VF 8",
    "VF 9",
  ],
  "VOLKSWAGEN": [
    "AMAROK",
    "AMEO",
    "ARTEON",
    "ARTEON SHOOTING BRAKE",
    "ATLAS",
    "ATLAS CROSS SPORT",
    "BEETLE",
    "BEETLE CABRIO",
    "CC",
    "CADDY",
    "CORRADO",
    "CROSS UP!",
    "DERBY",
    "EOS",
    "FOX",
    "GOL",
    "GOLF 3 DOORS",
    "GOLF 5 DOORS",
    "GOLF ALLTRACK",
    "GOLF CABRIO",
    "GOLF GTD VARIANT",
    "GOLF GTI / GTD / GTE",
    "GOLF GTI CABRIO",
    "GOLF PLUS",
    "GOLF R",
    "GOLF R CABRIO",
    "GOLF R VARIANT",
    "GOLF SPORTSVAN",
    "GOLF VARIANT",
    "ID. BUZZ",
    "ID.3",
    "ID.3 GTX",
    "ID.4",
    "ID.5",
    "ID.5 GTX",
    "ID.7",
    "ID.7 GTX TOURER",
    "ID.7 TOURER",
    "JETTA / VENTO / BORA",
    "JETTA GLI",
    "LAVIDA (CHINA)",
    "LUPO",
    "MULTIVAN",
    "NIVUS",
    "PASSAT",
    "PASSAT 3 DOORS",
    "PASSAT ALLTRACK",
    "PASSAT GTE",
    "PASSAT HATCHBACK",
    "PASSAT R",
    "PASSAT VARIANT",
    "PASSAT VARIANT GTE",
    "PHAETON",
    "POINTER",
    "POLO 3 DOORS",
    "POLO 5 DOORS",
    "POLO BLUEGT",
    "POLO COUPE",
    "POLO GTI",
    "POLO SEDAN",
    "POLO VARIANT",
    "ROUTAN",
    "SANTANA",
    "SCIROCCO",
    "SCIROCCO R",
    "SHARAN",
    "T-CROSS",
    "T-ROC",
    "T-ROC CABRIOLET",
    "T-ROC R",
    "TAIGO",
    "TIGUAN",
    "TIGUAN (US)",
    "TIGUAN ALLSPACE",
    "TOUAREG",
    "TOUAREG R",
    "TOURAN",
    "TRANSPORTER KOMBI",
    "VENTO",
    "XL1",
    "E-GOLF",
    "E-UP!",
    "UP!",
    "UP! GTI",
  ],
  "VOLVO": [
    "142",
    "144",
    "145",
    "244",
    "245",
    "262",
    "264",
    "265",
    "343",
    "345",
    "440",
    "460",
    "480",
    "66",
    "760",
    "760 ESTATE",
    "780",
    "850",
    "850 ESTATE",
    "940",
    "940 ESTATE",
    "960",
    "960 ESTATE",
    "C30",
    "C40",
    "C70",
    "C70 CONVERTIBLE",
    "C70 COUPE",
    "EM90",
    "EX30",
    "EX90",
    "P1800",
    "S40",
    "S60",
    "S60 CROSS COUNTRY",
    "S60 POLESTAR",
    "S70",
    "S80",
    "S90",
    "V40",
    "V40 CROSS COUNTRY",
    "V50",
    "V60",
    "V60 CROSS COUNTRY",
    "V60 POLESTAR",
    "V70",
    "V90",
    "V90 CROSS COUNTRY",
    "XC40",
    "XC60",
    "XC60 POLESTAR",
    "XC70",
    "XC90",
  ],
  "WIESMANN": [
    "GT MF4",
    "GT MF4-CS",
    "GT MF4-S",
    "GT MF5",
    "MF4 ROADSTER",
    "MF4-S ROADSTER",
    "MF5 ROADSTER",
  ],
  "XPENG": [
    "G3",
    "G6",
    "G9",
    "P5",
    "P7",
  ],
  "ZENDER": [
    "ESCAPE 6",
    "FACT 4 BITURBO",
    "FACT 4 SPIDER",
    "PROGETTO 5",
    "STRAIGHT 8",
    "THIRTY 7",
  ],
  "ZENVO": [
    "AURORA",
    "ST1",
    "TS1",
    "TSR-S",
  ],
};
